### ISSUE TITLE
[Rider][ReportedByUser] MS Azure Explorer - Error Loading Storage Accounts

### ISSUE THREAD

**Issue by tottes200** [JetBrains/azure-tools-for-intellij#428] opened 2020-12-29 19:20 UTC
IntelliJ build version: 2020.3.1 RD-203.6682.13
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.9.1
Plugin version: 3.46.0.1054-2020.3
Error message: 
```
com.intellij.openapi.progress.ProcessCanceledException
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorBase.throwIfCanceled(AbstractProgressIndicatorBase.java:145)
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorBase.checkCanceled(AbstractProgressIndicatorBase.java:136)
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorExBase.checkCanceled(AbstractProgressIndicatorExBase.java:101)
	at com.intellij.openapi.progress.impl.CoreProgressManager.doCheckCanceled(CoreProgressManager.java:133)
	at com.intellij.openapi.progress.ProgressManager.checkCanceled(ProgressManager.java:230)
	at com.intellij.serviceContainer.ContainerUtilKt.checkCanceledIfNotInClassInit(containerUtil.kt:82)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:460)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:440)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:25)
	at com.microsoft.intellij.AzureSettings.getSafeInstance(AzureSettings.java:51)
	at com.microsoft.intellij.helpers.IDEHelperImpl.getProperties(IDEHelperImpl.java:250)
	at com.microsoft.tooling.msservices.helpers.ExternalStorageHelper.getList(ExternalStorageHelper.

**Comment by maartenba** [comment] 2021-01-29 16:01
Could not reproduce this one. @tottes200 are you still seeing this error?

**Comment by maartenba** [comment] 2021-02-22 15:43
Closing this issue for now as we were not able to reproduce it. Feel free to re-open it if you see this happening again.

**Closed as completed by maartenba** 2021-02-22 15:43 UTC
Labels: bug
