### ISSUE TITLE
[Rider][ReportedByUser] MS Azure Explorer - Error Loading Blobs

### ISSUE THREAD

**Issue by AndriiKuznietsov** [JetBrains/azure-tools-for-intellij#326] opened 2020-06-22 08:44 UTC
IntelliJ build version: 2020.1.3 RD-201.7846.1
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.7
Plugin version: 3.35.0.651-2020.1
Error message: 
```
java.util.NoSuchElementException: An error occurred while enumerating the result, check the original exception for details.
	at com.microsoft.azure.storage.core.LazySegmentedIterator.hasNext(LazySegmentedIterator.java:113)
	at com.microsoft.tooling.msservices.helpers.azure.sdk.StorageClientSDKManager.getBlobContainers(StorageClientSDKManager.java:122)
	at com.microsoft.tooling.msservices.helpers.azure.sdk.StorageClientSDKManager.getBlobContainers(StorageClientSDKManager.java:113)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.storage.asm.ClientBlobModule.refreshItems(ClientBlobModule.java:47)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode.refreshItems(RefreshableNode.java:95)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode$2.run(RefreshableNode.java:161)
	at com.microsoft.intellij.helpers.IDEHelperImpl$2$1.run(IDEHelperImpl.java:141)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:932)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:434)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:233)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProc

**Comment by maartenba** [comment] 2020-06-22 10:42
Duplicate of #206

**Closed as completed by maartenba** 2020-06-22 10:42 UTC
