### ISSUE TITLE
[Rider][ReportedByUser] MS Azure Explorer - Error Loading Blobs

### ISSUE THREAD

**Issue by ser2ver** [JetBrains/azure-tools-for-intellij#193] opened 2019-05-07 07:26 UTC
IntelliJ build version: 2019.1 EAP RD-191.6733.1035
OS: Linux
JDK: JetBrains s.r.o 1.8.0_202-release
Plugin version: 3.20.0.449-2019.1
Error message: 
```
java.util.NoSuchElementException: An error occurred while enumerating the result, check the original exception for details.
	at com.microsoft.azure.storage.core.LazySegmentedIterator.hasNext(LazySegmentedIterator.java:113)
	at com.microsoft.tooling.msservices.helpers.azure.sdk.StorageClientSDKManager.getBlobContainers(StorageClientSDKManager.java:122)
	at com.microsoft.tooling.msservices.helpers.azure.sdk.StorageClientSDKManager.getBlobContainers(StorageClientSDKManager.java:113)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.storage.asm.ClientBlobModule.refreshItems(ClientBlobModule.java:47)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode.refreshItems(RefreshableNode.java:95)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode$2.run(RefreshableNode.java:161)
	at com.microsoft.intellij.helpers.IDEHelperImpl$2$1.run(IDEHelperImpl.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:731)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessU

**Comment by maartenba** [comment] 2019-05-07 07:36
@ser2ver Any chance you could share Rider logs with us at well? (feel free to do so privately via email - maarten AT jetbrains.com)

**Comment by maartenba** [comment] 2019-10-17 20:35
Duplicate of #206

**Closed as completed** 2019-11-19 06:43 UTC
Labels: bug, duplicate
