### ISSUE TITLE
`java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.

### ISSUE THREAD

**Issue by kirfalk** [JetBrains/azure-tools-for-intellij#15] opened 2018-09-13 14:49 UTC
Rider 2018.2.3 RTM 182.4231.496
Azure pluing : 3.11.0

Repro : 
- create a simple WebApp .netcore
- start to Publish it to Azure
- stop Publishing process

`java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:59)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: rx.exceptions.OnErrorFailedException: Error occurred when trying to propagate error to Observer.onError
	at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:187)
	at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)
	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.onError(OperatorSubscribeOn.java:80)
	at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:212)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:50)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	... 7 more
Caused by: rx.exceptions.CompositeException: 2 exceptions occurred. 
	... 17 more
Caused by: rx.exceptions.CompositeException$CompositeExceptionCausalChain: Chain of Causes for CompositeException In Order Received =>
	at rx.exceptions.CompositeException.getCause(CompositeException.java:129)
	at java.lang.Throwable.printEnclosedStackTrace(Throwable.java:707)
	at java.lang.Throwable.printEnclosedStackTrace(Throwable.java:709)
	at java.lang.Throwable.printStackTrace(Throwable.java:667)
	at java.lang.Throwable.printStackTrace(Throwable.java:721)
	at org.apache.log4j.DefaultThrowableRenderer.render(DefaultThrowableRenderer.java:60)
	at com.intellij.idea.IdeaLogger.lambda$static$1(IdeaLogger.java:54)
	at org.apache.log4j.spi.ThrowableInformation.getThrowableStrRep(ThrowableInformation.java:89)
	at org.apache.log4j.spi.LoggingEvent.getThrowableStrRep(LoggingEvent.java:413)
	at org.apache.log4j.WriterAppender.subAppend(WriterAppender.java:313)
	at org.apache.log4j.RollingFileAppender.subAppend(RollingFileAppender.java:276)
	at org.apache.log4j.WriterAppender.append(WriterAppender.java:162)
	at org.apache.log4j.AppenderSkeleton.doAppend(AppenderSkeleton.java:251)
	at org.apache.log4j.helpers.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:66)
	at org.apache.log4j.Category.callAppenders(Category.java:206)
	at org.apache.log4j.Category.forcedLog(Category.java:391)
	at org.apache.log4j.Category.error(Category.java:322)
	at com.intellij.idea.IdeaLogger.error(IdeaLogger.java:115)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:153)
	at com.intellij.ide.plugins.PluginManager.processException(PluginManager.java:145)
	at com.intellij.ide.plugins.PluginManager$1.uncaughtException(PluginManager.java:63)
	at rx.internal.schedulers.ScheduledAction.signalError(ScheduledAction.java:68)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:59)
	... 7 more
Caused by: java.lang.Error: The process has been terminated
	at com.microsoft.intellij.runner.RunProcessHandler.println(RunProcessHandler.java:86)
	at com.microsoft.intellij.runner.RunProcessHandler.setText(RunProcessHandler.java:120)
	at com.microsoft.intellij.runner.webapp.webappconfig.RiderWebAppRunState.zipDeploy(RiderWebAppRunState.kt:385)
	at com.microsoft.intellij.runner.webapp.webappconfig.RiderWebAppRunState.deployToAzureWebApp(RiderWebAppRunState.kt:355)
	at com.microsoft.intellij.runner.webapp.webappconfig.RiderWebAppRunState.executeSteps(RiderWebAppRunState.kt:117)
	at com.microsoft.intellij.runner.webapp.webappconfig.RiderWebAppRunState.executeSteps(RiderWebAppRunState.kt:36)
	at com.microsoft.intellij.runner.AzureRunProfileState.lambda$execute$0(AzureRunProfileState.java:62)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:48)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	... 7 more
Caused by: java.lang.Error: The process has been terminated
	at com.microsoft.intellij.runner.RunProcessHandler.println(RunProcessHandler.java:86)
	at com.microsoft.intellij.runner.webapp.webappconfig.RiderWebAppRunState.onFail(RiderWebAppRunState.kt:156)
	at com.microsoft.intellij.runner.AzureRunProfileState.lambda$execute$2(AzureRunProfileState.java:70)
	at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44)
	at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:153)
	at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)
	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.onError(OperatorSubscribeOn.java:80)
	at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:212)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:50)
	... 12 more`

**Comment by maartenba** [comment] 2020-01-07 11:01
Could not reproduce, closing for now.

**Closed by maartenba** 2020-01-07 11:01 UTC
