### ISSUE TITLE
func.exe passed as argument to func.exe

### ISSUE THREAD

**Issue by sga-solita** [JetBrains/azure-tools-for-intellij#646] opened 2022-11-10 09:06 UTC
Azure Functions Core Tools (1.0.28)
Function Runtime Version: 1.0.13154.0

I have  a weird issue when I attempt to debug an azure function, the func.exe-path is passed as an argument to func.exe (see screenshot)
![image](https://user-images.githubusercontent.com/78082425/201047478-965ca2e0-2350-4867-9381-96620ec1717e.png)

The error doesn't happen when I use Run (without debug)

Maybe related, maybe not, for some reason I can't see Azure Functions Version v1 in Settings for Azure:
![image](https://user-images.githubusercontent.com/78082425/201048576-b981c0d5-de17-4c3c-a1e8-cc82b60de45f.png)

**Comment by maartenba** [comment] 2022-11-10 13:48
Azure Functions v1 is not officially supported, which is why you are not seeing it there.

Could you post a screenshot of the generated run configuration by any chance?

**Comment by sga-solita** [comment] 2022-11-11 06:18
Alright, although I think my azure function is v1.

Here is a screenshot of the run configuration (which I didnt edit)
![image](https://user-images.githubusercontent.com/78082425/201276175-2987068c-d027-4e12-b437-dd714290a7e3.png)

**Comment by maartenba** [comment] 2022-11-15 10:35
Have not yet been able to reproduce the issue. Would you mind e-mailing a copy of the `workspace.xml` in your `.idea` folder to maarten at jebrains?

**Comment by maartenba** [comment] 2023-01-04 12:59
Root cause: we should use MsNet for v1 functions instead of .NET Core.

**Comment by maartenba** [comment] 2023-01-05 07:52
Fix merged and will release an updated plugin later this week. Thanks @sgacommentor for your help in troubleshooting this one!

**Closed as completed** 2023-01-05 07:52 UTC
Labels: discussion

**Comment by sga-solita** [comment] 2023-01-05 09:33
No problem, happy to be able to help!
