### ISSUE TITLE
[Rider][ReportedByUser] MS Azure Explorer - Error Loading Blobs

### ISSUE THREAD

**Issue by nshCore** [JetBrains/azure-tools-for-intellij#254] opened 2019-10-17 20:25 UTC
IntelliJ build version: 2019.2.2 RD-192.6584.65
OS: Mac OS X
JDK: JetBrains s.r.o 11.0.3
Plugin version: 3.26.0.534-2019.2
Error message: 
```
java.util.NoSuchElementException: An error occurred while enumerating the result, check the original exception for details.
	at com.microsoft.azure.storage.core.LazySegmentedIterator.hasNext(LazySegmentedIterator.java:113)
	at com.microsoft.tooling.msservices.helpers.azure.sdk.StorageClientSDKManager.getBlobContainers(StorageClientSDKManager.java:122)
	at com.microsoft.tooling.msservices.helpers.azure.sdk.StorageClientSDKManager.getBlobContainers(StorageClientSDKManager.java:113)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.storage.asm.ClientBlobModule.refreshItems(ClientBlobModule.java:47)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode.refreshItems(RefreshableNode.java:95)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode$2.run(RefreshableNode.java:161)
	at com.microsoft.intellij.helpers.IDEHelperImpl$2$1.run(IDEHelperImpl.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:894)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgre

**Comment by maartenba** [comment] 2019-11-19 06:43
Duplicate of #206

**Closed as completed by maartenba** 2019-11-19 06:43 UTC
Labels: bug, duplicate
