### ISSUE TITLE
Timeout when publishing Azure Web App with long build time

### ISSUE THREAD

**Issue by megla-tlanghorst** [JetBrains/azure-tools-for-intellij#529] opened 2021-10-07 13:14 UTC
If I publish a Web App that has a long build (a few minutes) it will timeout:
```
Got existing Web App with Id: '<censored>'
Collecting '<censored>' project artifacts...
Fail publishing ZIP file: java.util.concurrent.TimeoutException
Fail publishing ZIP file
```
If I build it once and build therefore skips some steps and runs quicker the publish is successful (tried it many times and it's quite consistent, I haven't timed it but after a certain time it fails).
It should probably either enforce no timeout or at least be configurable.

**Comment by megla-tlanghorst** [comment] 2021-10-07 13:18
Just timed it and it's happening after almost exact 3 minutes.

**Comment by maartenba** [comment] 2021-10-07 13:24
Thanks for reporting! The 3 minutes is indeed hardcoded. Will close this issue (it is a duplicate of #529) and look into it 👍

**Closed as completed by maartenba** 2021-10-07 13:24 UTC
Labels: bug

**Comment by megla-tlanghorst** [comment] 2021-10-07 13:26
> 
> 
> Thanks for reporting! The 3 minutes is indeed hardcoded. Will close this issue (it is a duplicate of #529) and look into it 👍

Did you mean to quote a different issue? Because #529 is this issue.

**Comment by maartenba** [comment] 2021-10-07 13:35
Of course, need more coffee... #437 is the one
