### ISSUE TITLE
Latest Version Missing Run Icon in Source of a Function

### ISSUE THREAD

**Issue by ilushka85** [JetBrains/azure-tools-for-intellij#354] opened 2020-08-18 12:18 UTC
We used to be able to right click and run / debug a specific function as well as see the green run button to the left of the code.  This is now gone.  How can it be fixed?

**Comment by maartenba** [comment] 2020-08-18 13:22
@ilushka85 Rider will recognize your functions only when:
* Project file has the tools version specified, e.g. `<AzureFunctionsVersion>v3</AzureFunctionsVersion>`
* Project file has a reference to `Microsoft.NET.Sdk.Functions`
* Project contains a `host.json` file

Is it a project where this worked before, or a new one? 

When the above is all good, would you mind to send us Rider logs and report them using the instruction here - https://rider-support.jetbrains.com/hc/en-us/articles/360001079770-How-to-collect-Rider-logs- ?

cc @sdubov Could this be back-end not loading properly?

**Comment by ilushka85** [comment] 2020-08-18 13:57
All the above are true... and this is a project(s) that worked previously...
[rider-logs-20200818-085612.zip](https://github.com/JetBrains/azure-tools-for-intellij/files/5090793/rider-logs-20200818-085612.zip)

**Comment by maartenba** [comment] 2020-08-18 14:37
Thanks, we'll look into it!

In the meanwhile, could you try uninstalling the plugin, restart Rider, reinstall, restart again? I am suspecting part of the plugin wasn't picked up while loading.

**Comment by ilushka85** [comment] 2020-08-18 17:51
Tried uninstall restarting and reinstalling and restarting and did not work

**Comment by maartenba** [comment] 2020-08-20 06:14
Was investigating #355, which could be related. @ilushka85, by any chance, is your `host.json` a linked file instead of a direct project item?

**Comment by ilushka85** [comment] 2020-08-20 12:07
It is not.

**Comment by sdubov** [comment] 2020-08-27 16:25
Hi @ilushka85. There are some checks behind gutter mark for Function method. Let's first understand if those conditions are true as well. We check method is "public", "static" and has attribute `Microsoft.Azure.WebJobs.FunctionNameAttribute`.  Could you please provide a signature for a method you use as a Function, so, we could check it on our side? 

Could you also please check a latest Rider 2020.2.1? There should be some fixes including lookup error from your log file. Could you please check on latest Rider if you see the same problem? If yes - then, could you please enable trace logging for Completion and Daemon (Help | Diagnostic Tools | Choose Trace Scenarios -> Daemon, Completion) and re-send us logs please?

**Comment by ilushka85** [comment] 2020-08-28 13:22
My methods are public and have the attribute added.  Again this worked in all of my solutions before but now it works in none.  Attached is the log 
[idea.log.zip](https://github.com/JetBrains/azure-tools-for-intellij/files/5142263/idea.log.zip)

**Comment by sdubov** [comment] 2020-08-28 13:47
Thank you for checking @ilushka85. What plugin version did you use previously? We fully rewrote the gutter mark detection logic in `3.35.0.725-2020.2` version (migrated it from front-end to ReSharper backend side - https://github.com/JetBrains/azure-tools-for-intellij/pull/307). This could cause some issues with detection for edge cases.

**Comment by ilushka85** [comment] 2020-08-30 02:05
3.40.0.879-2020.2

**Comment by ilushka85** [comment] 2020-09-02 13:27
The latest update solved the issue.

**Comment by maartenba** [comment] 2020-09-02 13:39
Nice, thanks for letting us know @ilushka85 !

**Comment by ilushka85** [comment] 2020-09-02 13:40
Correction... after restarting again it no longer appears anymore.

**Comment by ilushka85** [comment] 2020-09-03 11:16
Any updates on this issue ?

**Comment by sdubov** [comment] 2020-09-03 11:40
@ilushka85, unfortunately, idea logs does not contain logic for registering function app highlighters. Gutter marks are registered in a backend and I would like to check if required highlighter was registered in your Rider instance. Could you please attach `backend.log` as well from the run (with enabled tracing)?

**Comment by ilushka85** [comment] 2020-09-03 13:02
Here are the backend logs 


[Archive.zip](https://github.com/JetBrains/azure-tools-for-intellij/files/5168623/Archive.zip)

**Comment by ilushka85** [comment] 2020-09-08 17:52
Any updates on this issue?

**Comment by sdubov** [comment] 2020-09-09 10:53
@ilushka85, may I ask you for some additional info to debug the problem on our side? Could you please send me a minimal function example you are using (function signature with attributes)?

**Comment by ilushka85** [comment] 2020-09-11 13:14
public  class AzureUserSync
    {
        private readonly UserSync _userSync;
        public AzureUserSync(UserSync userSync)
        {
            _userSync=userSync;
        }
        [FunctionName("AzureUserSync")]
        public async Task RunAsync([TimerTrigger("0 */5 * * * *")] TimerInfo myTimer, ILogger log)
        {
            await _userSync.SyncUsers();

        }
    }

**Comment by sdubov** [comment] 2020-09-14 11:37
Got it. We skip the DI function definition at the moment. `static` modifier is one of the thing that we check to show gutter mark for a method as I mentioned above. We will need to update the logic here. Thank you for investigation.

**Comment by ilushka85** [comment] 2020-09-14 21:35
Is this a recent change ?  As it worked in previous version.

**Comment by ilushka85** [comment] 2020-09-14 21:37
I can confirm that as soon as I insert the word static between public and async in the sample the green run icon appears.

**Comment by sdubov** [comment] 2020-09-15 10:08
> Is this a recent change ? As it worked in previous version.

It was here since we moved gutter marks highlighters from IDEA to R# process. It was released in `3.35.0.725-2020.2` plugin version.

**Closed as completed** 2020-09-15 13:39 UTC
Labels: discussion

**Comment by maartenba** [comment] 2020-09-15 15:23
@ilushka85 We'll publish a plugin update in the coming weeks.

**Comment by dietergoetelen** [comment] 2023-01-18 08:08
I can reproduce this issue when relative line numbers are enabled in `.ideavimrc`. It was working fine before, not sure which update (ideavim/azure toolbox) introduced this regression.

**Comment by maartenba** [comment] 2023-01-18 09:18
@dietergoetelen seems to be ok here
![image](https://user-images.githubusercontent.com/485230/213131955-8a18d3f0-2828-4e82-a57e-6d082488fff8.png)

Would you mind trying a **File | Invalidate caches**?

**Comment by dietergoetelen** [comment] 2023-01-18 12:59
@maartenba thank you for the fast response and solution, looks like it's working again 🥳
