### ISSUE TITLE
[Rider][ReportedByUser] MS Azure Explorer - Error Loading SQL Databases

### ISSUE THREAD

**Issue by doshub** [JetBrains/azure-tools-for-intellij#440] opened 2021-02-04 13:46 UTC
IntelliJ build version: 2020.3.2 RD-203.6682.21
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.9.1
Plugin version: 3.46.0.1054-2020.3
Error message: 
```
java.lang.RuntimeException: java.io.IOException: Authorization is required, please sign out and sign in again
	at rx.exceptions.Exceptions.propagate(Exceptions.java:57)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:463)
	at rx.observables.BlockingObservable.single(BlockingObservable.java:340)
	at com.microsoft.azure.management.sql.implementation.ServersInner.list(ServersInner.java:209)
	at com.microsoft.azure.management.resources.fluentcore.arm.collection.implementation.TopLevelModifiableResourcesImpl.list(TopLevelModifiableResourcesImpl.java:118)
	at com.microsoft.azuretools.core.mvp.model.database.AzureSqlServerMvpModel.getSqlServersBySubscriptionId(AzureSqlServerMvpModel.kt:157)
	at com.microsoft.azuretools.core.mvp.model.database.AzureSqlServerMvpModel.listSqlServersBySubscriptionId(AzureSqlServerMvpModel.kt:62)
	at com.microsoft.azuretools.core.mvp.model.database.AzureSqlServerMvpModel.listSqlServers(AzureSqlServerMvpModel.kt:97)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.database.AzureDatabaseModulePresenter.onModuleRefresh(AzureDatabaseModulePresenter.kt:44)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.database.AzureDatabaseModule.refreshItems(AzureDatabaseModule.kt:46)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNo

**Comment by maartenba** [comment] 2021-02-04 15:20
Duplicate of #438 in terms of surfacing the `Authorization is required, please sign out and sign in again` message better

**Closed as completed by maartenba** 2021-02-04 15:20 UTC
