### ISSUE TITLE
java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.

### ISSUE THREAD

**Issue by libin049** [JetBrains/azure-tools-for-intellij#324] opened 2020-06-19 09:18 UTC
![image](https://user-images.githubusercontent.com/7247717/85117117-ec4fc500-b250-11ea-8c7b-091a5ee26524.png)

**Comment by maartenba** [comment] 2020-06-19 10:11
Duplicate of #323

**Closed as completed** 2020-06-22 10:42 UTC
