### ISSUE TITLE
No Deployment Slots for Azure Functions Consumption Plan

### ISSUE THREAD

**Issue by kwasak** [JetBrains/azure-tools-for-intellij#263] opened 2019-12-02 16:17 UTC
Deployment Slots for Azure Function Apps do not show up in Azure Explorer or in the deploy window located in build configuration options.

I do however see deployment slots for a web app with a monthly app service plan.

**Comment by maartenba** [comment] 2019-12-02 17:53
Thanks for reporting. Going to close as a duplicate of #72

**Closed as completed** 2019-12-02 17:53 UTC
Labels: duplicate
