### ISSUE TITLE
Cannot find Azure Core Functions Tools

### ISSUE THREAD

**Issue by ciwchris** [JetBrains/azure-tools-for-intellij#944] opened 2024-10-25 05:23 UTC
I just downloaded Rider. When starting up Rider for the first time when prompted for plugins I selected the Azure Toolkit for Rider. Rider finished starting up.

I click the "New Solution" icon and selected "Azure Functions. I'm presented with a window prompting me to "Download Azure Function Core Tools". I click the link. It downloads the tools. I click "Configure Azure Function Core Tools". A window pops up showing me the Core Tools Paths for each version of the tools, which are set to "Managed by Rider". I confirm the "Tool download path" contains a downloaded version of the Core Tools. I click "Save", even though I made no changes. I'm still presented with the page prompting me to download the Core Tools.

I've also tried to manually download the Core Tools through npm as well as from the releases page in GitHub. I then update the v4 path in Rider to either of these versions of the Core Tools. Yet the page still prompts me to download the Core Tools. Outside of Rider in the terminal I can run `func` just fine.

Rider: Build #RD-242.23726.100, built on October 22, 2024
Azure Toolkit for Rider: 4.2.2
Azure Function Core Tools: 4.0.6280
Fedora Linux 41
Any ideas on why Rider does not detect the Core Tools?

**Comment by Thomas-Carstensen** [comment] 2024-10-25 08:59
I have the same Issue while running on Windows 11.

Same version of Rider, Azure Toolkit and Azure Function Core Tools.

I tried downgrading but the issue persisted on:
Rider: 2024.1.6 Build 233.15026.35
Azure Toolkit: 3.50.01784-2024.1

**Comment by Radioh** [comment] 2024-10-25 10:06
I have the same issue. Not sure if upgrading Rider caused the issue, but it persisted after a downgrade.

For me, it looks like this workaround resolved the issue for now:
Rider -> Settings -> Tools -> Azure -> Functions -- and then set Azure Function Version from 'Managed by Rider' to 'From environment PATH'.

**Comment by rafaelldi** [comment] 2024-10-25 10:20
Hi! Unfortunately, there is a possible bug in the Azure core tools feed https://github.com/Azure/azure-functions-tooling-feed/issues/587. We'll try to fix it on our side.

**Comment by Thomas-Carstensen** [comment] 2024-10-25 12:37
> I have the same issue. Not sure if upgrading Rider caused the issue, but it persisted after a downgrade.
> 
> For me, it looks like this workaround resolved the issue for now: Rider -> Settings -> Tools -> Azure -> Functions -- and then set Azure Function Version from 'Managed by Rider' to 'From environment PATH'.

When switching away from the 'Managed By Rider' option, my function host fails to start with the following message

```
Azure Functions host did not return isolated worker process id. Could not attach the debugger. Check the process output for more information.
```

What arguments are you passing to the func cli?

**Comment by rafaelldi** [comment] 2024-10-25 13:33
Hello! The issue should be fixed in the 4.2.3 version. Please remove the `v4` folder inside the `{HOME FOLDER}/.AzureToolsForIntelliJ/AzureFunctionsCoreTools/`, the plugin should redownload core tools.

**Comment by Radioh** [comment] 2024-10-25 13:36
Nice work @rafaelldi - Can confirm it works after deleting V4 folder with the new version.

**Comment by rafaelldi** [comment] 2024-10-25 13:37
Thanks for checking!

**Comment by mickvikt** [comment] 2024-10-25 13:42
Worked for me as well,  @rafaelldi, thanks!

**Comment by TheAxeDude** [comment] 2024-10-25 14:06
@rafaelldi Ive updated the plugin & deleted the v4 folder. The folder returns, but remains empty:

<img width="222" alt="image" src="https://github.com/user-attachments/assets/214024a8-b2fa-4bfe-b741-c10341e7f96c">


I've tried re-installing the plugin - any ideas?

**Comment by rafaelldi** [comment] 2024-10-25 14:10
@TheAxeDude Do you have `<AzureFunctionsVersion>V3</AzureFunctionsVersion>`  property in your project?

**Comment by TheAxeDude** [comment] 2024-10-25 14:11
@rafaelldi  no, in this project all are set to 		

`<AzureFunctionsVersion>V4</AzureFunctionsVersion>`

**Comment by rafaelldi** [comment] 2024-10-25 14:16
I'm investigating this

**Comment by c-falardeau** [comment] 2024-10-25 15:15
I use v4, removed the folder and still have the issue. I have removed the v4 folder and it appear back again, but I get the same error (`Azure Functions host did not return isolated worker process id. Could not attach the debugger. Check the process output for more information.`).

 I have also made sure no other Azure Core Tools were installed on my computer

**Comment by ciwchris** [comment] 2024-10-25 15:17
For some reason it can no longer download, unzip and copy the Core Tools to ~/.AzureToolsForIntelliJ/AzureFunctionsCoreTools/v4. I see this error:

> Can't unzip /tmp/AzureFunctions-v4-4.100.0.zip

Looking in my `tmp` directory I see a AzureFunctions-v4-4.100.0.temp folder which contains the Core Tools. After manually copying the contents to ~/.AzureToolsForIntelliJ/AzureFunctionsCoreTools/v4 then Rider sees the Core Tools.

Although the "Create" button is still disabled

**Comment by rafaelldi** [comment] 2024-10-25 19:05
Looks like the fix only works on Windows. I'll make another fix. Really sorry for the inconvenience.

**Comment by sonettmorten** [comment] 2024-10-27 07:08
The workaround of using ENV PATH for Azure Functions works in Mac OS ARM64 using the latest versions of the IDE and the plugin. I hope it's possible to find a proper solution for this soon :)

**Comment by sanjaybhagia** [comment] 2024-10-27 23:12
I'm using: 
JetBrains Rider 2024.1.6

Azure Toolkit for Rider: 3.50.0.1784-2024.1

Hardware: Macbook Pro (Apple M2 Max)
OS: macOS Sequoia  Version 15.0 (24A335)

I'm still getting the issue. Changing ENV PATH dosn't work for me either as others are suggesting.

**Comment by Xaxage** [comment] 2024-10-27 23:52
> I'm using: JetBrains Rider 2024.1.6
> 
> Azure Toolkit for Rider: 3.50.0.1784-2024.1
> 
> Hardware: Macbook Pro (Apple M2 Max) OS: macOS Sequoia Version 15.0 (24A335)
> 
> I'm still getting the issue. Changing ENV PATH dosn't work for me either as others are suggesting.

Before finding this issue - I downloaded locally via Homebrew Azure functions toolkit. It was downloaded by default to opt folder. In the rider I gave that path and it worked

**Comment by sanjaybhagia** [comment] 2024-10-27 23:53
> > I'm using: JetBrains Rider 2024.1.6
> > Azure Toolkit for Rider: 3.50.0.1784-2024.1
> > Hardware: Macbook Pro (Apple M2 Max) OS: macOS Sequoia Version 15.0 (24A335)
> > I'm still getting the issue. Changing ENV PATH dosn't work for me either as others are suggesting.
> 
> Before finding this issue - I downloaded locally via Homebrew Azure functions toolkit. It was downloaded by default to opt folder. In the rider I gave that path and it worked

Do you mind sharing the path?

**Comment by PoyaManouchehri** [comment] 2024-10-27 23:54
> I'm using: JetBrains Rider 2024.1.6
> 
> Azure Toolkit for Rider: 3.50.0.1784-2024.1
> 
> Hardware: Macbook Pro (Apple M2 Max) OS: macOS Sequoia Version 15.0 (24A335)
> 
> I'm still getting the issue. Changing ENV PATH dosn't work for me either as others are suggesting.

Not sure if you are running into the same issue as me, but in order to use ENV PATH you need to install Azure Functions Toolkit yourself. If you use Homebrew you can run this:

```
brew tap azure/functions
brew install azure-functions-core-tools@4
```

This should update your Environment Path which Rider can then use.

**Comment by sanjaybhagia** [comment] 2024-10-27 23:55
> > I'm using: JetBrains Rider 2024.1.6
> > Azure Toolkit for Rider: 3.50.0.1784-2024.1
> > Hardware: Macbook Pro (Apple M2 Max) OS: macOS Sequoia Version 15.0 (24A335)
> > I'm still getting the issue. Changing ENV PATH dosn't work for me either as others are suggesting.
> 
> Not sure if you are running into the same issue as me, but in order to use ENV PATH you need to install Azure Functions Toolkit yourself. If you use Homebrew you can run this:
> 
> ```
> brew tap azure/functions
> brew install azure-functions-core-tools@4
> ```
> 
> This should update your Environment Path which Rider can then use.

Thanks. Yeah i have tried that already but doesn't seem to work for me. Changing from Managed by Rider to ENV doesn't seem to have any impact. Tried restarting the IDE after the change as well.

**Comment by PoyaManouchehri** [comment] 2024-10-28 00:00
> Thanks. Yeah i have tried that already but doesn't seem to work for me. Changing from Managed by Rider to ENV doesn't seem to have any impact. Tried restarting the IDE after the change as well.

For what it's worth, after selecing "From Environment PATH" and Saving, the path was changed to `/opt/homebrew/Cellar/azure-functions-core-tools@4/4.0.6280/func`.

**Comment by sanjaybhagia** [comment] 2024-10-28 01:23
> > Thanks. Yeah i have tried that already but doesn't seem to work for me. Changing from Managed by Rider to ENV doesn't seem to have any impact. Tried restarting the IDE after the change as well.
> 
> For what it's worth, after selecing "From Environment PATH" and Saving, the path was changed to `/opt/homebrew/Cellar/azure-functions-core-tools@4/4.0.6280/func`.

Thanks for your help @PoyaManouchehri. 

Didn't help for some reason, it's not setting the correct path for me when I do apply this change.

**Comment by sanjaybhagia** [comment] 2024-10-28 02:01
Alright got it to work. Got a new update for Rider, after upgrading. It still didn't work for me. After the update, I deleted v4 folder for Rider's path and after that, it didn't download it. 

Eventually, I uninstalled the function tools, installed them again. change the setting to read from ENV in Rider and it started working for me.

**Comment by danr-stadion** [comment] 2024-10-28 08:45
I'm getting the error after updating to the latest Azure plugin for Rider on Windows:

![image](https://github.com/user-attachments/assets/046ced1f-25cb-4055-8f6f-4246e5e94913)

I had managed to get it working but this update has broken it again. Very frustrating.

JetBrains Rider 2024.2.7
Build #RD-242.23726.100, built on October 22, 2024
Runtime version: 21.0.4+13-b509.26 amd64 (JCEF 122.1.9)
Windows 11.0
.NET Core v8.0.4 x64 (Server GC)
Registry:
  ide.experimental.ui=true
  i18n.locale=
Non-Bundled Plugins:
  org.intellij.plugins.hcl (242.23339.11)
  com.jetbrains.space (242.23726.16)
  com.intellij.plugin.adernov.powershell (2.8.0)
  com.intellij.resharper.azure (4.2.3)

**Comment by rafaelldi** [comment] 2024-10-28 10:11
Hello, folks. Please try the new `4.2.4` version. The problem should be fixed there. We'll use the previous release of Azure core tools, and in the meantime, we'll find out what's going on with the current one.

**Comment by Xaxage** [comment] 2024-10-28 10:28
> @rafaelldi Ive updated the plugin & deleted the v4 folder. The folder returns, but remains empty:
> 
> <img alt="image" width="222" src="https://private-user-images.githubusercontent.com/573138/380197816-214024a8-b2fa-4bfe-b741-c10341e7f96c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxMTEyMjcsIm5iZiI6MTczMDExMDkyNywicGF0aCI6Ii81NzMxMzgvMzgwMTk3ODE2LTIxNDAyNGE4LWIyZmEtNGJmZS1iNzQxLWMxMDM0MWU3Zjk2Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOFQxMDIyMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NDE2MzY5YmRiZTRhZDdlNjI3MmM3ZmE5MzIzYTdiZDgyZTQyMzdkNTRmOWFkODM0MjU4NmQyZTA0NTRkZGFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.lTDwhiX81IC9ZBgVyIXia2thIgVCqnXgvRgw58kgnFo">
> I've tried re-installing the plugin - any ideas?

I testes on Mac M1 pro it works. Just one question. What is the default path for the "Tool download path" ? 
I've changed it several times and want to be sure. No I set it to .AzureToolsForIntelliJ directory.

**Comment by Xaxage** [comment] 2024-10-28 10:28
> Hello, folks. Please try the new `4.2.4` version. The problem should be fixed there. We'll use the previous release of Azure core tools, and in the meantime, we'll find out what's going on with the current one.

I've tested on Mac M1 pro and it works now. 
Just one question. What is the default path for the "Tool download path" ?
I've changed it several times manually and want to be sure. Now I set it to .AzureToolsForIntelliJ directory.

**Comment by Martijnr85** [comment] 2024-10-28 10:42
After the update is was able to debug and run my azure function again

**Comment by rafaelldi** [comment] 2024-10-28 10:50
@Xaxage The default value is {HOME FOLDER}/.AzureToolsForIntelliJ/AzureFunctionsCoreTools/

**Closed as completed** 2024-10-28 10:51 UTC

**Comment by KungFuCookie** [comment] 2024-10-28 12:21
Same issue for me on Mac ARM.
Env Variable doesnt seem to be working for me but, you can manually point the path for v4 to the following after installing via homebrew:
/opt/homebrew/Cellar/azure-functions-core-tools@4/4.0.6280
![image](https://github.com/user-attachments/assets/122de28e-030a-4e67-b311-8f2cca899062)

the opt folder is hidden in the root of the HD using command . (period) to view the hidden files

The v4 which rider installs, doesnt seem to have the right structure under this location, but HomeBrew location is fine
/Users/{user}/.AzureToolsForIntelliJ/AzureFunctionsCoreTools/

**Comment by batonkarton** [comment] 2024-10-28 16:28
Hello @rafaelldi 
Unfortunately, I still face this issue after updating the plugin to the 4.2.4 version.
I tried different approaches: managed by the rider, with the environment path, manually provided the path to npm core tools (with and without func.exe)
Also, I removed and re-install everything - tools and plugins :)
For me, only using func start from the terminal and attaching it to the process works.

Win 11
Rider 2024.2.7
npm Func azure-functions-core-tools 4.0.6280 - just npm, one version
![image](https://github.com/user-attachments/assets/6de4c4b4-8080-4ca7-9b19-e8ff1f638c42)
![image](https://github.com/user-attachments/assets/305cf95d-41e4-40ea-af0e-05b6accde485)
![image](https://github.com/user-attachments/assets/6a8accac-9d84-4aaa-8f71-0d50128ac627)
![image](https://github.com/user-attachments/assets/38343b0b-f504-49a4-a356-6a50a3896e5d)

**Comment by rafaelldi** [comment] 2024-10-29 08:42
@batonkarton Hi! No, it looks like a separate problem (especially since you have it reproduced with npm tools). Could you please create a new issue for your problem?

**Comment by danr-stadion** [comment] 2024-10-29 08:44
I'm now experiencing a different issue after upgrading to the latest version of the tools (4.2.4). The function attempts to start, but I get this error in the debug console:

```
Azure Functions Core Tools
Core Tools Version:       4.0.6518 Commit hash: N/A +74ed9095fdd6c5326276aae6b8a7d41ccbdeb6aa (64-bit)
Function Runtime Version: 4.35.4.23179

[2024-10-29T08:37:04.950Z] Found C:\xxx\xxx.Functions.csproj. Using for user secrets file configuration.
[2024-10-29T08:37:06.851Z] Error building configuration in an external startup class.
[2024-10-29T08:37:06.852Z] Error building configuration in an external startup class. xxx.Functions: Could not load file or assembly 'Microsoft.Extensions.Configuration.Abstractions, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
[2024-10-29T08:37:06.961Z] A host error has occurred during startup operation 'afc52337-a9d2-459e-91dd-d73cab20c35b'.
[2024-10-29T08:37:06.962Z] Microsoft.Azure.WebJobs.Script: Error building configuration in an external startup class. LiveLike.Functions: Could not load file or assembly 'Microsoft.Extensions.Configuration.Abstractions, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
Value cannot be null. (Parameter 'provider')
Press any key to continue....
```

This function works perfectly when deployed into Azure, but Rider fails to start it locally.

Any help with this would be very much appreciated.

Thanks,
Dan.

```
JetBrains Rider 2024.2.7
Build #RD-242.23726.100, built on October 22, 2024
Runtime version: 21.0.4+13-b509.26 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.windows.WToolkit
Windows 11.0
.NET Core v8.0.4 x64 (Server GC)
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 4074M
Cores: 12
Registry:
  ide.experimental.ui=true
  i18n.locale=
Non-Bundled Plugins:
  org.intellij.plugins.hcl (242.23339.11)
  com.jetbrains.space (242.23726.16)
  com.intellij.plugin.adernov.powershell (2.8.0)
  com.intellij.resharper.azure (4.2.4)
```

**Comment by batonkarton** [comment] 2024-10-29 13:38
> Unfortunately, I still face this issue after updating the plugin to the 4.2.4 version. I tried different approaches: managed by the rider, with the environment path, manually provided the path to npm core tools (with and without func.exe) Also, I removed and re-install everything - tools and plugins :) For me, only using func start from the terminal and attaching it to the process works.
> 
> Win 11 Rider 2024.2.7 npm Func azure-functions-core-tools 4.0.6280 - just npm, one version

Just don't want to mislead folks who read this :)
I've tried to use the next commands in the debug configuration before the fixes by @rafaelldi : 
`func start --pause-on-error --port 7075 --dotnet-isolated-debug`
`host start --pause-on-error --port 7075 --dotnet-isolated-debug`
For both of them, I received the same error related to attaching the debugger: `Azure Functions host process terminated before the debugger could attach.`

After fixes, in the current time, I'm still facing this issue only for 
`func start --pause-on-error --port 7075 --dotnet-isolated-debug`
In result:
`host start --pause-on-error --port 7075 --dotnet-isolated-debug` starts working for me.

**Comment by mentrixmax** [comment] 2024-10-29 15:01
For me, MAC M1 - Works update the Rider to Version 

JetBrains Rider 2024.2.7
Build #RD-242.23726.100, built on October 22, 2024
Licensed to Mateus A Alves
Subscription is active until May 19, 2025.
For educational use only.
Runtime version: 21.0.4+13-b509.26 aarch64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.lwawt.macosx.LWCToolkit
macOS 15.0.1
.NET Core v8.0.4 ARM64 (Server GC)
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
  i18n.locale=
Non-Bundled Plugins:
  com.intellij.ml.llm (242.23726.20)
  com.intellij.resharper.azure (4.2.4)

**Comment by rafaelldi** [comment] 2024-10-30 08:10
@danr-stadion Hi! It seems like the error comes from Azure core tools, not from Rider. You could try manually run `func host start --pause-on-error --port 7156 --dotnet-isolated-debug`  and check if the error appears. Anyway, this doesn't relate to the original issue, so it's better to create a separate one.

**Comment by danr-stadion** [comment] 2024-10-30 08:38
> @danr-stadion Hi! It seems like the error comes from Azure core tools, not from Rider. You could try manually run `func host start --pause-on-error --port 7156 --dotnet-isolated-debug` and check if the error appears. Anyway, this doesn't relate to the original issue, so it's better to create a separate one.

Understood. Only reason I posted here was because this was all working before the latest updates to the Rider Azure tools plugin, so thought it might be relevant.

**Comment by ramonesteban78** [comment] 2024-10-30 10:35
> Azure/azure-functions-tooling-feed#587

This finally works for me!!

**Comment by ramonesteban78** [comment] 2024-10-30 10:36
> Same issue for me on Mac ARM. Env Variable doesnt seem to be working for me but, you can manually point the path for v4 to the following after installing via homebrew: /opt/homebrew/Cellar/azure-functions-core-tools@4/4.0.6280 ![image](https://private-user-images.githubusercontent.com/43062388/380710742-122de28e-030a-4e67-b311-8f2cca899062.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyODQ4MDgsIm5iZiI6MTczMDI4NDUwOCwicGF0aCI6Ii80MzA2MjM4OC8zODA3MTA3NDItMTIyZGUyOGUtMDMwYS00ZTY3LWIzMTEtOGYyY2NhODk5MDYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDEwMzUwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmYjExOWRiZjdiYTVlZDk1MTQyOTFkZTZjMzRlMTUxNzcwNjNkYmI1YmYwNjZkMDk5NDA3MGQwMTk5MWI4ZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.AzyQJx1ByXbqZXTsINVmg-_IzV3DLXKhoIoSSqIC1VM)
> 
> the opt folder is hidden in the root of the HD using command . (period) to view the hidden files
> 
> The v4 which rider installs, doesnt seem to have the right structure under this location, but HomeBrew location is fine /Users/{user}/.AzureToolsForIntelliJ/AzureFunctionsCoreTools/

This works for me finally!! Thanks @KungFuCookie !

**Comment by rafaelldi** [comment] 2024-10-31 13:07
@danr-stadion This may be related to the new version of the core tools. It is possible that something has changed there. You can try running manually to check the root cause. Feel free to open a new issue.

**Comment by rafaelldi** [comment] 2024-10-31 13:10
@KungFuCookie @ramonesteban78 With the latest version `v4.2.4` of the plugin, everything should work automatically (without the need to manually set the path to the core tools). Do you still experience the problem?

**Comment by evilsquirr3l** [comment] 2024-11-01 08:08
@rafaelldi I just updated to v4.2.4 and now I have the error:
`"Error running '<function name was here>' java. lang. IllegalStateException: Expected a string but was BEGIN_OBJECT at line 34 column 20 path $.ConnectionStrings."`

**Comment by KungFuCookie** [comment] 2024-11-01 10:08
> @KungFuCookie @ramonesteban78 With the latest version `v4.2.4` of the plugin, everything should work automatically (without the need to manually set the path to the core tools). Do you still experience the problem?

Hmm tried to retest, I set it back to Managed By Rider deleted the v4 /Users/{user}/.AzureToolsForIntelliJ/AzureFunctionsCoreTools/
and updated Rider to latest. However it keeps installing 4.101.0 when launching and still fails with the:
Can't run Azure Functions host. No Azure Functions Core Tools information could be determined.

But I can see a new version is available!! I will update again : JetBrains Rider 2024.2.7 available

Success!

/Users/stevecooke/.AzureToolsForIntelliJ/AzureFunctionsCoreTools/v4/4.99.0/func host start --pause-on-error

Azure Functions Core Tools
Core Tools Version:       4.0.6280 Commit hash: N/A +421f0144b42047aa289ce691dc6db4fc8b6143e6 (64-bit)
Function Runtime Version: 4.834.3.22875

**Comment by UcheIgbokwe** [comment] 2024-11-04 12:33
Upgrading to version  2024.2.7 solved this issue for me.

**Comment by skellyneill** [comment] 2025-02-20 04:01
For those still having this issue after attempting all the solutions in the thread, I managed to resolve the issue by:
- Set your Core Tools path back to being managed by Rider
- [Download](https://github.com/Azure/azure-functions-core-tools/releases) the in azure function in-process CLI version you need. E.g.  Azure.Functions.Cli.min.win-x64_inproc.4.0.6518
- Create the appropriate folder for the version you're using: {HomeFolder}/.AzureToolsForIntelliJ/AzureFunctionsCoreTools/v4
- Unzip the tool into the :arrow_up: folder

FYI I am using:
- Rider 2024.3.5
- Azure Toolkit for Rider 4.3.9
